# Generated by Django 5.0.6 on 2024-06-01 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0002_experiencias_suscriptor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
