# Generated by Django 5.0.6 on 2024-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0003_alter_video_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencias',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='experiencias',
            name='historia',
            field=models.TextField(max_length=1000),
        ),
    ]
