# Generated by Django 5.0.6 on 2024-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0004_experiencias_fecha_alter_experiencias_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurvivalTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='survival_tools/')),
            ],
        ),
    ]
