# Generated by Django 5.0.6 on 2024-06-20 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0005_survivaltool'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
