# Generated by Django 5.0.6 on 2024-06-20 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0006_video_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suscriptor',
        ),
    ]
