# Generated by Django 5.0.6 on 2024-06-21 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appcoder', '0008_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='author',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='staff_only',
        ),
    ]
